# Plugin Configuration for Neuro-OS
# Controls which plugins are enabled and their settings

plugins:
  chrome_integration:
    # Enhanced Chrome browser integration
    enabled: true
    priority: high
    settings:
      # Enable Chrome DevTools Protocol for deeper integration
      use_devtools: false
      # Enable accessibility API integration  
      use_accessibility: true
      # Cache web page analysis results
      cache_page_analysis: true
      cache_duration: 30  # seconds
    applications:
      - "chrome.exe"
      - "msedge.exe"
      - "firefox.exe"
  
  vs_code_integration:
    # VS Code / IDE integration (placeholder for future)
    enabled: false
    priority: medium
    settings:
      use_language_server: true
      enable_code_completion: true
    applications:
      - "code.exe"
      - "devenv.exe"
  
  office_integration:
    # Microsoft Office integration (placeholder for future)  
    enabled: false
    priority: medium
    settings:
      enable_document_analysis: true
    applications:
      - "winword.exe"
      - "excel.exe"
      - "powerpnt.exe"

regionalization:
  # Core regionalization settings
  update_interval: 2.0  # seconds
  max_regions: 50      # maximum regions to track
  confidence_threshold: 0.6  # minimum confidence for region detection
  
  # Performance settings
  screenshot_quality: medium  # low, medium, high
  enable_caching: true
  cache_duration: 1.0  # seconds
  
  # Detection settings
  detect_buttons: true
  detect_text_inputs: true
  detect_menus: true
  detect_toolbars: true
  detect_tabs: true

context_system:
  # Context generation settings
  max_context_age: 5.0  # seconds
  enable_performance_monitoring: true
  
  # Context types to include
  include_visual: true
  include_semantic: true  
  include_interactive: true
  include_temporal: false  # Disable for performance
  include_application: true
  
  # Message formatting
  max_message_length: 2000  # characters
  include_performance_info: true
  include_plugin_info: true

# Application-specific overrides
applications:
  "chrome.exe":
    plugins:
      - chrome_integration
    regionalization:
      update_interval: 1.5  # Faster updates for browsers
      detect_web_elements: true
  
  "notepad.exe":
    regionalization:
      update_interval: 3.0  # Slower updates for simple apps
      
  "explorer.exe":
    regionalization:
      detect_file_items: true
      update_interval: 2.5