# Neuro-OS Debug Configuration
debug:
  enabled: true
  trace:
    enabled: true
    verbose: false
    show_file_path: false
    show_timestamp: true
    max_value_len: 60
    max_locals: 4
    max_stack_depth: 12
    use_color: true
    include_paths:
      - "src/dev"
      - "src/tests"
    exclude_functions:
      - "write_log"
      - "trace"
      - "__enter__"
      - "__exit__"
    events:
      - "call"
      - "return" 
      - "exception"
      # - "line"  # Uncomment for very verbose line-by-line tracing
  logging:
    level: "INFO"
    file: "logs/neuro_os_debug.log"
    console: true

connection:
  retry:
    max_attempts: 10
    initial_delay: 5
    max_delay: 60
    backoff_multiplier: 1.5

performance:
  websocket:
    ping_interval: 30
    ping_timeout: 10
    max_message_size: 1048576  # 1MB